python start_month_uzy.py --month_offset 0
python start_month_uzy.py --month_offset 2
python start_month_uzy.py --month_offset 4
python start_month_uzy.py --month_offset 6
python start_month_uzy.py --month_offset 8
python start_month_uzy.py --month_offset 10
python start_month_uzy.py --month_offset 12
python start_month_uz.py --month_offset 0
python start_month_uz.py --month_offset 2
python start_month_uz.py --month_offset 4
python start_month_uz.py --month_offset 6
python start_month_uz.py --month_offset 8
python start_month_uz.py --month_offset 10
python start_month_uz.py --month_offset 12
