python weather_uzy.py --cloud_offset_year 0
python weather_uzy.py --cloud_offset_year 10
python weather_uzy.py --cloud_offset_year 20
python weather_uzy.py --cloud_offset_year 30
python weather_uzy.py --cloud_offset_year 1
python weather_uzy.py --cloud_offset_year 11
python weather_uzy.py --cloud_offset_year 21
python weather_uzy.py --cloud_offset_year 31
python weather_uzy.py --cloud_offset_year 35
python weather_uzy.py --cloud_offset_year 36
python weather_uz.py --cloud_offset_year 0
python weather_uz.py --cloud_offset_year 10
python weather_uz.py --cloud_offset_year 20
python weather_uz.py --cloud_offset_year 30
python weather_uz.py --cloud_offset_year 1
python weather_uz.py --cloud_offset_year 11
python weather_uz.py --cloud_offset_year 21
python weather_uz.py --cloud_offset_year 31
python weather_uz.py --cloud_offset_year 35
python weather_uz.py --cloud_offset_year 36
