python franken_supress.py --repeat_weight 0
python franken_supress.py --repeat_weight 1
python franken_supress.py --repeat_weight 2
python franken_supress.py --repeat_weight 10
python franken_supress.py --repeat_weight 20
python franken_supress.py --repeat_weight 50
python franken_supress.py --repeat_weight 100
python franken_supress_fp.py --repeat_weight 0
python franken_supress_fp.py --repeat_weight 1
python franken_supress_fp.py --repeat_weight 2
python franken_supress_fp.py --repeat_weight 10
python franken_supress_fp.py --repeat_weight 20
python franken_supress_fp.py --repeat_weight 50
python franken_supress_fp.py --repeat_weight 100
